### ISSUE TITLE
Module 3.1 Hyperlink Issue

### ISSUE THREAD

**Issue by ecieszynski** [cooperrc/computational-mechanics#50]
The hyper link for event connections does not work anymore. 

![image](https://user-images.githubusercontent.com/106542680/173461784-d4622b80-2eb3-47b5-aece-ec6130ad6d53.png)

**Comment by cooperrc** [comment]
Thanks for pointing out the error!

Can you add a link to the page where it's referenced?

**Comment by cooperrc** [comment]
Looks like it should be this link

https://matplotlib.org/3.5.0/users/explain/event_handling.html

in section 

https://cooperrc.github.io/computational-mechanics/module_03/01_Catch_Motion.html#capture-mouse-clicks-on-the-frame
